# base
default:
  image: registry.git.insea.io/sail/aisci/image_registry/zhengkh/jax_xc:0.0.1
  before_script:
    - pip config unset global.index-url
    - pip config unset global.trusted-host
  tags:
    - sail

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - make flake8

yapf:
  stage: lint
  script:
    - make py-format

clang:
  stage: lint
  script:
    - make clang-format

cpplint:
  stage: lint
  script:
    - make cpplint

buildifier:
  stage: lint
  script:
    - make buildifier

test:
  stage: test
  script:
    - bazel test --test_output=all --action_env=PATH=$PATH:$MAPLE_PATH --remote_cache=http://bazel-cache-http.ai.seacloud.garenanow.com //tests/...
