# base
default:
  image: registry.git.insea.io/sail/sail-engineering/golden-images/python_bazel_golden:latest
  before_script:
    - pip config unset global.index-url
    - pip config unset global.trusted-host
  tags:
    - sail

stages:
  - lint

flake8:
  stage: lint
  script:
    - make flake8

yapf:
  stage: lint
  script:
    - make py-format

clang:
  stage: lint
  script:
    - make clang-format

cpplint:
  stage: lint
  script:
    - make cpplint

buildifier:
  stage: lint
  script:
    - make buildifier
